version: '3.8'

services:
  postgres_olist:
    image: postgres:latest
    container_name: postgres_olist
    environment:
      POSTGRES_USER: olistuser
      POSTGRES_PASSWORD: olistpass
      POSTGRES_DB: olist_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./data:/data
      - ./infra_setup/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - olist_network

  metabase:
    image: metabase/metabase:latest
    container_name: metabase-olist
    depends_on:
      - postgres_olist
    restart: always
    networks:
      - olist_network
    ports:
      - "3000:3000"


volumes:
  postgres_data:

networks:
  olist_network:
    driver: bridge
