version: 2

models:
  - name: customers
    description: this table houses customer information

    columns:
      - name: customer_id

      - name: customer_unique_id

      - name: customer_zip_code_prefix

      - name: customer_city

      - name: customer_state

  - name: geolocation
    description: this table contains geolocation data
  
    columns:
      - name: geolocation_zip_code_prefix

      - name: geolocation_lat

      - name: geolocation_lng

      - name: geolocation_city

      - name: geolocation_state
